# -*- coding: utf-8 -*-
"""xdefi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0Iw-q9vDks9ynE-pg6TScEUBXhagRfe
"""

pip install uniswap-python

from uniswap import Uniswap

address = None          # or None if you're not going to make transactions
private_key = None  # or None if you're not going to make transactions
version = 2                       # specify which version of Uniswap to use
provider = "https://mainnet.infura.io/v3/4149340e93ff495bb94cb7e54558e0fc"   
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider)

# Some token addresses 
eth = "0x0000000000000000000000000000000000000000"
bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
dai = "0x6B175474E89094C44Da98b954EedeAC495271d0F"

# Returns the amount of DAI you get for 1 ETH (10^18 wei)
k = uniswap.get_price_input(eth, dai, 10**18)
m = k/10**18
print(m)

# Returns the amount of ETH you need to pay (in wei) to get 1000 DAI
uniswap.get_price_output(eth, dai, 1_000 * 10**18)